# TGSoul Configuration
# Plugin by TGSoul - Compatible with MC 1.20-1.21.8 and GeyserMC

soul:
  # Starting number of souls for new players
  starting: 3
  
  # Maximum number of souls a player can have
  max: 3
  
  # Material used for soul items (both Java and Bedrock)
  material: "GHAST_TEAR"
  
  # What happens when a player reaches 0 souls
  # Options: permanent, temp, spectator
  ban-mode: "permanent"
  
  # Ban duration (only used if ban-mode is "temp")
  # Format: 1d, 7d, 1h, 30m, etc.
  ban-time: "7d"
  
  # Allow players to be revived using Revival Token
  allow-revive: true
  
  # Revival Token settings
  revival-token:
    # Material for the Revival Token
    material: "BEACON"
    
    # Recipe for Revival Token (3x3 crafting grid)
    recipe:
      a11: "NETHERITE_BLOCK"
      a12: "NETHER_STAR"
      a13: "NETHERITE_BLOCK"
      a21: "SOUL_SAND"  # This will be replaced with the target player's soul items
      a22: "SOUL_SAND"  # This will be replaced with the target player's soul items
      a23: "SOUL_SAND"  # This will be replaced with the target player's soul items
      a31: "NETHERITE_BLOCK"
      a32: "NETHER_STAR"
      a33: "NETHERITE_BLOCK"
  
  # Particle effects (limited for 1.20 compatibility)
  effects:
    # Effect when losing souls (death, withdraw, admin take)
    lose:
      particle: "SMOKE_NORMAL"  # Compatible with 1.20
      color: "GRAY"
      count: 20
      enabled: true
    
    # Effect when gaining souls (right-click, revive, admin give)
    gain:
      particle: "VILLAGER_HAPPY"  # Compatible with 1.20
      color: "GREEN"
      count: 15
      enabled: true
  
  # Advanced particle effects for 1.21+ (automatically disabled for 1.20)
  advanced-effects:
    lose:
      particle: "DUST"  # For 1.21+ with custom colors
      color: "#808080"  # Gray
      size: 1.0
    gain:
      particle: "DUST"
      color: "#00FF00"  # Green
      size: 1.0

# Messages
messages:
  prefix: "&8[&6TG Soul&8] &r"
  
  # Soul management
  souls-remaining: "&7You have &6{souls}&7 souls remaining."
  soul-lost: "&cYou lost a soul! &7({souls} remaining)"
  soul-gained: "&aYou gained a soul! &7({souls} total)"
  soul-withdrawn: "&7You withdrew a soul as an item."
  soul-consumed: "&aYou consumed a soul item!"
  
  # Death and revival
  death-message: "&c{player} died and lost a soul! &7({souls} souls remaining)"
  soul-dropped: "&7A soul was dropped at your death location."
  revive-success: "&a{player} has been revived with {souls} souls!"
  revive-failed: "&cRevival failed! Missing soul items for {player}."
  revive-not-needed: "&7{player} doesn't need to be revived."
  revival-token-placed: "&aRevival Token placed! {player} has been revived at this location!"
  revival-token-used: "&aYou have been revived by {reviver} using a Revival Token!"
  revival-token-no-target: "&cThis Revival Token has no target player!"
  
  # Punishment
  banned-permanent: "&cYou have been permanently banned for losing all souls! Only admins can unban you now."
  banned-temporary: "&cYou have been banned for {time} for losing all souls!"
  spectator-mode: "&7You are now in spectator mode. Use a Revival Token to be revived!"
  
  # Errors
  not-your-soul: "&cThis soul doesn't belong to you!"
  max-souls: "&7You already have the maximum number of souls."
  no-souls: "&cYou don't have any souls to withdraw!"
  player-not-found: "&cPlayer not found!"
  invalid-amount: "&cInvalid amount!"
  wrong-soul-owner: "&cYou can only use your own souls!"
  
  # Admin
  admin-gave-souls: "&7Gave &6{amount}&7 souls to &6{player}&7."
  admin-took-souls: "&7Took &6{amount}&7 souls from &6{player}&7."
  admin-set-souls: "&7Set &6{player}'s&7 souls to &6{amount}&7."
  admin-unbanned: "&7Unbanned &6{player}&7 and restored their souls."
  config-reloaded: "&aConfiguration reloaded!"
  
  # Help messages
  help-header: "&6&l=== TGSoul Help ==="
  help-soul: "&6/soul &7- Check your soul count"
  help-soul-help: "&6/soul help &7- Show this help menu"
  help-soul-recipe: "&6/soul recipe &7- View Revival Token recipe"
  help-soul-top: "&6/soul top [limit] &7- View top players by souls"
  help-soul-stats: "&6/soul stats [player] &7- View player statistics"
  help-soulwithdraw: "&6/soulwithdraw &7- Withdraw a soul as an item"
  help-revive: "&6/revive <player> &7- Revive a player (admin only)"
  help-admin-header: "&c&lAdmin Commands:"
  help-admin-give: "&c/soul give <player> <amount> &7- Give souls to a player"
  help-admin-take: "&c/soul take <player> <amount> &7- Take souls from a player"
  help-admin-set: "&c/soul set <player> <amount> &7- Set player's souls"
  help-admin-get: "&c/soul get <player> &7- Check player's souls"
  help-admin-reload: "&c/soul reload &7- Reload configuration"
  help-admin-unban: "&c/soul unban <player> &7- Unban and restore a player"
  
  # Recipe GUI
  recipe-gui-title: "&6Revival Token Recipe"
  recipe-gui-info: "&7Place these items in a crafting table to create a Revival Token"
  recipe-gui-soul-info: "&7Use 3 of YOUR OWN souls in these positions"

# Database settings (for future expansion)
database:
  type: "yaml"  # Currently only YAML supported
  auto-save: true
  save-interval: 300  # seconds

# GeyserMC compatibility
geyser:
  # Enable special handling for Bedrock players
  enabled: true
  
  # Custom item handling for Bedrock clients
  bedrock-items:
    # Use same material for both Java and Bedrock
    soul-item: "GHAST_TEAR"
    
  # Particle adjustments for Bedrock
  bedrock-particles:
    # Reduce particle count for better performance on mobile
    multiplier: 0.5